package android.hardware.bydauto.location;

import android.hardware.IBYDAutoEvent;
import android.hardware.IBYDAutoListener;
import android.hardware.bydauto.BYDAutoEventValue;

/**
 * Compile-only stub of the firmware listener base class; see bydauto-stubs/build.gradle.kts.
 * Generated by scripts/gen-bydauto-listener-stubs.py — do not edit by hand.
 *
 * onDataChanged is final in the firmware (it dispatches into the typed callbacks), so the push
 * listeners override onDataEventChanged — the universal hook that carries the raw fid.
 */
public abstract class AbsBYDAutoLocationListener implements IBYDAutoListener {

    @Override
    public final void onDataChanged(IBYDAutoEvent event) {
    }

    @Override
    public void onDataEventChanged(int eventType, BYDAutoEventValue eventValue) {
    }

    @Override
    public void onError(int errCode, String errMessage) {
    }
}
