#!/usr/bin/env python3
"""Generates the compile-only listener stubs and the recorder listener subclasses.

Source of truth is the decompiled firmware: every
`android/hardware/bydauto/<pkg>/AbsBYDAuto<X>Listener.java` that implements IBYDAutoListener
becomes

  1. a stub in bydauto-stubs (abstract class, final onDataChanged, open onDataEventChanged/onError),
  2. a Kotlin subclass in the app's helper/push package, wired to the recorder sink.

A listener without a device carrying a numeric mDeviceType is still stubbed, but gets no entry in
recorderListenerFor (nothing could register it).

Usage: scripts/gen-bydauto-listener-stubs.py [--fw <decompiled sources root>]
Prints the dev -> device class map for FID_PUSH_DEVICE_CLASSES at the end.
"""

import argparse
import pathlib
import re
import sys

DEFAULT_FW = (
    ".research/leopard3-pulled-fw20260514/decompiled/framework/sources/android/hardware/bydauto"
)
STUB_ROOT = "bydauto-stubs/src/main/java/android/hardware/bydauto"
LISTENERS_KT = "app/src/main/kotlin/com/bydmate/app/helper/push/FidRecorderListeners.kt"

STUB_TEMPLATE = """package android.hardware.bydauto.{pkg};

import android.hardware.IBYDAutoEvent;
import android.hardware.IBYDAutoListener;
import android.hardware.bydauto.BYDAutoEventValue;

/**
 * Compile-only stub of the firmware listener base class; see bydauto-stubs/build.gradle.kts.
 * Generated by scripts/gen-bydauto-listener-stubs.py — do not edit by hand.
 *
 * onDataChanged is final in the firmware (it dispatches into the typed callbacks), so the push
 * listeners override onDataEventChanged — the universal hook that carries the raw fid.
 */
public abstract class {cls} implements IBYDAutoListener {{

    @Override
    public final void onDataChanged(IBYDAutoEvent event) {{
    }}

    @Override
    public void onDataEventChanged(int eventType, BYDAutoEventValue eventValue) {{
    }}

    @Override
    public void onError(int errCode, String errMessage) {{
    }}
}}
"""

KT_HEADER = '''package com.bydmate.app.helper.push

import android.hardware.bydauto.BYDAutoEventValue
@IMPORTS@

/**
 * One listener subclass per BYD device, for the diagnostic fid recorder. Generated by
 * scripts/gen-bydauto-listener-stubs.py out of the decompiled firmware — do not edit by hand.
 *
 * The firmware rejects a dynamic Proxy over IBYDAutoListener, so every device needs a real
 * subclass of its own Abs class; the base classes only differ in the typed callbacks, which the
 * recorder does not use. These run on a vendor binder thread — the override hands the numbers to
 * [FidPushSink] (which swallows throwables) and does nothing else.
 *
 * The push channel keeps its own four listeners in FidPushListeners.kt: a recorder run must be
 * unregisterable on its own, without touching a live push subscription.
 */

/** The recorder listener for [device], or null when the firmware has no listener class for it. */
internal fun recorderListenerFor(device: Int, sink: FidPushSink): Any? =
    RECORDER_LISTENERS[device]?.invoke(sink)

/** Device id -> the listener subclass the firmware accepts for it. */
private val RECORDER_LISTENERS: Map<Int, (FidPushSink) -> Any> = mapOf(
'''


def read_devices(fw: pathlib.Path, constants: dict) -> dict:
    """package -> (device class name, device id). Packages without a numeric type are skipped."""
    devices = {}
    for path in sorted(fw.glob("*/BYDAuto*Device.java")):
        text = path.read_text(errors="replace")
        match = re.search(r"mDeviceType = (\d+)", text)
        dev = int(match.group(1)) if match else None
        if dev is None:
            match = re.search(r"mDeviceType = BYDAutoConstants\.([A-Z_0-9]+)", text)
            if match:
                dev = constants.get(match.group(1))
        if dev is None:
            print(f"skip (no numeric mDeviceType): {path.parent.name}", file=sys.stderr)
            continue
        devices[path.parent.name] = (path.stem, dev)
    return devices


def read_constants(fw: pathlib.Path) -> dict:
    text = (fw / "BYDAutoConstants.java").read_text(errors="replace")
    return {
        name: int(value)
        for name, value in re.findall(r"(BYDAUTO_DEVICE_[A-Z_0-9]+) = (\d+)", text)
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fw", default=DEFAULT_FW)
    args = parser.parse_args()

    root = pathlib.Path(__file__).resolve().parent.parent
    fw = pathlib.Path(args.fw)
    if not fw.is_absolute():
        fw = root / fw
    if not fw.is_dir():
        print(f"firmware sources not found: {fw}", file=sys.stderr)
        return 1

    constants = read_constants(fw)
    devices = read_devices(fw, constants)

    listeners = []  # (package, listener class, short name)
    for path in sorted(fw.glob("*/AbsBYDAuto*Listener.java")):
        text = path.read_text(errors="replace")
        if "implements IBYDAutoListener" not in text:
            print(f"skip (not an IBYDAutoListener): {path.parent.name}", file=sys.stderr)
            continue
        short = path.stem[len("AbsBYDAuto"):-len("Listener")]
        listeners.append((path.parent.name, path.stem, short))

    for pkg, cls, _ in listeners:
        out = root / STUB_ROOT / pkg / f"{cls}.java"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(STUB_TEMPLATE.format(pkg=pkg, cls=cls))

    imports = "\n".join(
        f"import android.hardware.bydauto.{pkg}.{cls}" for pkg, cls, _ in listeners
    )
    branches = []
    classes = []
    for pkg, cls, short in listeners:
        if pkg not in devices:
            continue
        _, dev = devices[pkg]
        branches.append(f"    {dev} to {{ sink -> Rec{short}Listener(sink) }},")
        classes.append(
            f"internal class Rec{short}Listener(private val sink: FidPushSink) : {cls}() {{\n"
            f"    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =\n"
            f"        sink.onRecorderEvent(eventType, eventValue)\n"
            f"}}"
        )
    body = KT_HEADER.replace("@IMPORTS@", imports)
    body += "\n".join(sorted(branches, key=lambda line: int(line.split()[0])))
    body += "\n)\n\n"
    body += "\n\n".join(classes)
    body += "\n"
    (root / LISTENERS_KT).write_text(body)

    print(f"stubs: {len(listeners)}  recorder listeners: {len(branches)}")
    print("FID_PUSH_DEVICE_CLASSES (paste into FidPushWire.kt):")
    for pkg, (cls, dev) in sorted(devices.items(), key=lambda kv: kv[1][1]):
        print(f'    {dev} to "android.hardware.bydauto.{pkg}.{cls}",')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
