package com.bydmate.app.helper.push

import android.hardware.bydauto.BYDAutoEventValue
import android.hardware.bydauto.ac.AbsBYDAutoAcListener
import android.hardware.bydauto.adas.AbsBYDAutoADASListener
import android.hardware.bydauto.audio.AbsBYDAutoAudioListener
import android.hardware.bydauto.auxiliary.AbsBYDAutoAuxListener
import android.hardware.bydauto.bigdata.AbsBYDAutoBigDataListener
import android.hardware.bydauto.bodywork.AbsBYDAutoBodyworkListener
import android.hardware.bydauto.charging.AbsBYDAutoChargingListener
import android.hardware.bydauto.collision.AbsBYDAutoCollisionListener
import android.hardware.bydauto.doorlock.AbsBYDAutoDoorLockListener
import android.hardware.bydauto.doormirror.AbsBYDAutoRearViewMirrorListener
import android.hardware.bydauto.energy.AbsBYDAutoEnergyListener
import android.hardware.bydauto.engine.AbsBYDAutoEngineListener
import android.hardware.bydauto.funcnotice.AbsBYDAutoFuncNoticeListener
import android.hardware.bydauto.gb.AbsBYDAutoGBListener
import android.hardware.bydauto.gearbox.AbsBYDAutoGearboxListener
import android.hardware.bydauto.instrument.AbsBYDAutoInstrumentListener
import android.hardware.bydauto.light.AbsBYDAutoLightListener
import android.hardware.bydauto.location.AbsBYDAutoLocationListener
import android.hardware.bydauto.motor.AbsBYDAutoMotorListener
import android.hardware.bydauto.mqtt.AbsBYDAutoMqttListener
import android.hardware.bydauto.ota.AbsBYDAutoOtaListener
import android.hardware.bydauto.panorama.AbsBYDAutoPanoramaListener
import android.hardware.bydauto.phone.AbsBYDAutoPhoneListener
import android.hardware.bydauto.pm2p5.AbsBYDAutoPM2p5Listener
import android.hardware.bydauto.power.AbsBYDAutoPowerListener
import android.hardware.bydauto.qcfs.AbsBYDAutoQcfsListener
import android.hardware.bydauto.radar.AbsBYDAutoRadarListener
import android.hardware.bydauto.radio.AbsBYDAutoRadioListener
import android.hardware.bydauto.reminder.AbsBYDAutoReminderListener
import android.hardware.bydauto.rescue.AbsBYDAutoRescueListener
import android.hardware.bydauto.rse.AbsBYDAutoRSEListener
import android.hardware.bydauto.safetybelt.AbsBYDAutoSafetyBeltListener
import android.hardware.bydauto.security.AbsBYDAutoSecurityListener
import android.hardware.bydauto.sensor.AbsBYDAutoSensorListener
import android.hardware.bydauto.setting.AbsBYDAutoSettingListener
import android.hardware.bydauto.special.AbsBYDAutoSpecialListener
import android.hardware.bydauto.speed.AbsBYDAutoSpeedListener
import android.hardware.bydauto.statistic.AbsBYDAutoStatisticListener
import android.hardware.bydauto.test.AbsBYDAutoTestListener
import android.hardware.bydauto.time.AbsBYDAutoTimeListener
import android.hardware.bydauto.tyre.AbsBYDAutoTyreListener
import android.hardware.bydauto.vehicledata.AbsBYDAutoVehicleDataListener
import android.hardware.bydauto.version.AbsBYDAutoVersionListener
import android.hardware.bydauto.wiper.AbsBYDAutoWiperListener
import android.hardware.bydauto.yun.AbsBYDAutoYunListener

/**
 * One listener subclass per BYD device, for the diagnostic fid recorder. Generated by
 * scripts/gen-bydauto-listener-stubs.py out of the decompiled firmware — do not edit by hand.
 *
 * The firmware rejects a dynamic Proxy over IBYDAutoListener, so every device needs a real
 * subclass of its own Abs class; the base classes only differ in the typed callbacks, which the
 * recorder does not use. These run on a vendor binder thread — the override hands the numbers to
 * [FidPushSink] (which swallows throwables) and does nothing else.
 *
 * The push channel keeps its own four listeners in FidPushListeners.kt: a recorder run must be
 * unregisterable on its own, without touching a live push subscription.
 */

/** The recorder listener for [device], or null when the firmware has no listener class for it. */
internal fun recorderListenerFor(device: Int, sink: FidPushSink): Any? =
    RECORDER_LISTENERS[device]?.invoke(sink)

/** Device id -> the listener subclass the firmware accepts for it. */
private val RECORDER_LISTENERS: Map<Int, (FidPushSink) -> Any> = mapOf(
    1000 to { sink -> RecAcListener(sink) },
    1001 to { sink -> RecBodyworkListener(sink) },
    1002 to { sink -> RecAudioListener(sink) },
    1004 to { sink -> RecLightListener(sink) },
    1005 to { sink -> RecPowerListener(sink) },
    1006 to { sink -> RecEnergyListener(sink) },
    1007 to { sink -> RecInstrumentListener(sink) },
    1008 to { sink -> RecPM2p5Listener(sink) },
    1009 to { sink -> RecChargingListener(sink) },
    1010 to { sink -> RecSecurityListener(sink) },
    1011 to { sink -> RecGearboxListener(sink) },
    1012 to { sink -> RecEngineListener(sink) },
    1013 to { sink -> RecSpeedListener(sink) },
    1014 to { sink -> RecStatisticListener(sink) },
    1015 to { sink -> RecCollisionListener(sink) },
    1016 to { sink -> RecTyreListener(sink) },
    1017 to { sink -> RecLocationListener(sink) },
    1019 to { sink -> RecAuxListener(sink) },
    1020 to { sink -> RecMotorListener(sink) },
    1021 to { sink -> RecRadioListener(sink) },
    1022 to { sink -> RecTestListener(sink) },
    1023 to { sink -> RecSettingListener(sink) },
    1024 to { sink -> RecTimeListener(sink) },
    1025 to { sink -> RecRadarListener(sink) },
    1026 to { sink -> RecReminderListener(sink) },
    1027 to { sink -> RecVersionListener(sink) },
    1028 to { sink -> RecFuncNoticeListener(sink) },
    1029 to { sink -> RecPhoneListener(sink) },
    1031 to { sink -> RecPanoramaListener(sink) },
    1032 to { sink -> RecOtaListener(sink) },
    1033 to { sink -> RecMqttListener(sink) },
    1034 to { sink -> RecYunListener(sink) },
    1036 to { sink -> RecQcfsListener(sink) },
    1038 to { sink -> RecADASListener(sink) },
    1039 to { sink -> RecGBListener(sink) },
    1040 to { sink -> RecRescueListener(sink) },
    1041 to { sink -> RecDoorLockListener(sink) },
    1042 to { sink -> RecSafetyBeltListener(sink) },
    1043 to { sink -> RecSensorListener(sink) },
    1046 to { sink -> RecWiperListener(sink) },
    1047 to { sink -> RecRearViewMirrorListener(sink) },
    1048 to { sink -> RecVehicleDataListener(sink) },
    1049 to { sink -> RecSpecialListener(sink) },
    1061 to { sink -> RecBigDataListener(sink) },
    1062 to { sink -> RecRSEListener(sink) },
)

internal class RecAcListener(private val sink: FidPushSink) : AbsBYDAutoAcListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecADASListener(private val sink: FidPushSink) : AbsBYDAutoADASListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecAudioListener(private val sink: FidPushSink) : AbsBYDAutoAudioListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecAuxListener(private val sink: FidPushSink) : AbsBYDAutoAuxListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecBigDataListener(private val sink: FidPushSink) : AbsBYDAutoBigDataListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecBodyworkListener(private val sink: FidPushSink) : AbsBYDAutoBodyworkListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecChargingListener(private val sink: FidPushSink) : AbsBYDAutoChargingListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecCollisionListener(private val sink: FidPushSink) : AbsBYDAutoCollisionListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecDoorLockListener(private val sink: FidPushSink) : AbsBYDAutoDoorLockListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecRearViewMirrorListener(private val sink: FidPushSink) : AbsBYDAutoRearViewMirrorListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecEnergyListener(private val sink: FidPushSink) : AbsBYDAutoEnergyListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecEngineListener(private val sink: FidPushSink) : AbsBYDAutoEngineListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecFuncNoticeListener(private val sink: FidPushSink) : AbsBYDAutoFuncNoticeListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecGBListener(private val sink: FidPushSink) : AbsBYDAutoGBListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecGearboxListener(private val sink: FidPushSink) : AbsBYDAutoGearboxListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecInstrumentListener(private val sink: FidPushSink) : AbsBYDAutoInstrumentListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecLightListener(private val sink: FidPushSink) : AbsBYDAutoLightListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecLocationListener(private val sink: FidPushSink) : AbsBYDAutoLocationListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecMotorListener(private val sink: FidPushSink) : AbsBYDAutoMotorListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecMqttListener(private val sink: FidPushSink) : AbsBYDAutoMqttListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecOtaListener(private val sink: FidPushSink) : AbsBYDAutoOtaListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecPanoramaListener(private val sink: FidPushSink) : AbsBYDAutoPanoramaListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecPhoneListener(private val sink: FidPushSink) : AbsBYDAutoPhoneListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecPM2p5Listener(private val sink: FidPushSink) : AbsBYDAutoPM2p5Listener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecPowerListener(private val sink: FidPushSink) : AbsBYDAutoPowerListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecQcfsListener(private val sink: FidPushSink) : AbsBYDAutoQcfsListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecRadarListener(private val sink: FidPushSink) : AbsBYDAutoRadarListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecRadioListener(private val sink: FidPushSink) : AbsBYDAutoRadioListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecReminderListener(private val sink: FidPushSink) : AbsBYDAutoReminderListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecRescueListener(private val sink: FidPushSink) : AbsBYDAutoRescueListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecRSEListener(private val sink: FidPushSink) : AbsBYDAutoRSEListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecSafetyBeltListener(private val sink: FidPushSink) : AbsBYDAutoSafetyBeltListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecSecurityListener(private val sink: FidPushSink) : AbsBYDAutoSecurityListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecSensorListener(private val sink: FidPushSink) : AbsBYDAutoSensorListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecSettingListener(private val sink: FidPushSink) : AbsBYDAutoSettingListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecSpecialListener(private val sink: FidPushSink) : AbsBYDAutoSpecialListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecSpeedListener(private val sink: FidPushSink) : AbsBYDAutoSpeedListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecStatisticListener(private val sink: FidPushSink) : AbsBYDAutoStatisticListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecTestListener(private val sink: FidPushSink) : AbsBYDAutoTestListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecTimeListener(private val sink: FidPushSink) : AbsBYDAutoTimeListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecTyreListener(private val sink: FidPushSink) : AbsBYDAutoTyreListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecVehicleDataListener(private val sink: FidPushSink) : AbsBYDAutoVehicleDataListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecVersionListener(private val sink: FidPushSink) : AbsBYDAutoVersionListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecWiperListener(private val sink: FidPushSink) : AbsBYDAutoWiperListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}

internal class RecYunListener(private val sink: FidPushSink) : AbsBYDAutoYunListener() {
    override fun onDataEventChanged(eventType: Int, eventValue: BYDAutoEventValue?) =
        sink.onRecorderEvent(eventType, eventValue)
}
